### PR TITLE
feat: update built_path dependencies to latest versions

### PR DESCRIPTION
**Pull request by engineerdeep**
Updated dependencies of the package to the latest versions respectively and updated version to `0.2.0`.
Please suggest any additional changes if any and I will address them.

Edit: Migrated `built_path_annotations` to null safety.

Thank you for your support!

### CODE REVIEW

**Comment by dnfield** [comment]
What is this unblocking? :)

I haven't really looked much at this library and I'm not sure who's using it. I'm not opposed to this but I'm not clear on what it's fixing/unblocking.

**Comment by engineerdeep** [comment]
Thank you for your prompt response.

I wanted to try using this package to have a clickable world map from svgs, but since it's not updated I can't use it in my project as it conflicts with other dependencies that use a newer version of this packages dependencies (same as an open issue from about a year ago in this repo).

So thought I might as well raise a PR for anyone wanting to use this in the future. :)

**Comment by engineerdeep** [comment]
Apologies for changing the scope of the PR, I have migrated the `built_path_annotations` to null safety as well if you don't mind.

**Comment by engineerdeep** [comment]
@dnfield Would love it if you could help me merge this please.

**Comment by dnfield** [comment]
Thanks!

**Pull request merged**
